# 19.2.3
Позитивные тесты для методов калькулятора (+-*/)
В скринкасте в аргументах  также указывался аргумент self (assert self.calc.adding(self, 4, 3) == 7), но при запуске тестов PyCharm писал об ошибке о лишнем аргументе. После удаления self из аргументов (assert self.calc.adding(4, 3) == 7) тест проходил успешно
